services:
    phpbb.collapsiblecategories.listener:
        class: phpbb\collapsiblecategories\event\listener
        arguments:
            - @controller.helper
            - @phpbb.collapsiblecategories.operator
            - @template
        tags:
            - { name: event.listener }

    phpbb.collapsiblecategories.controller:
        class: phpbb\collapsiblecategories\controller\main_controller
        arguments:
            - @phpbb.collapsiblecategories.operator
            - @request

    phpbb.collapsiblecategories.operator:
        class: phpbb\collapsiblecategories\operator\operator
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @user
