services:
    bb3mobi.newtopic.listener:
        class: bb3mobi\newtopic\event\listener
        arguments:
            - @config
            - @request
            - @template
            - @auth
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
 