services:
    rxu.PostsMerging.listener:
        class: rxu\PostsMerging\event\listener
        arguments:
            - @config
            - @auth
            - @request
            - @user
            - @notification_manager
            - @dispatcher
            - @template
            - @rxu.PostsMerging.helper
            - %core.root_path%
            - %core.php_ext%
            - null
        tags:
            - { name: event.listener }
    rxu.PostsMerging.helper:
        class: rxu\PostsMerging\core\helper
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @user
            - %core.root_path%
            - %core.php_ext%
